tabScriptZones={}
hiddenZone
slots = 6
currentSlot = 0

onPickup
	teint = playerColor
end

reload
	supprime HiddenZone
	supprime scriptzones
	currentSlot = 0
end

roll
	supprime HiddenZone

	create Hiddenzone
	hiddenZone = guid

	create scriptzones
	tab.push guid

	currentSlot = random 1-slots
end

shoot
	if currentSlot+1 > slots
		currentSlot = 1
	else
		currentSlot++
	end
	grab items from tabScriptZones[currentSlot]
end
